version: "3.4"

services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "5010:80"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        ports:
          - "1433:1433"

        environment:
            MSSQL_SA_PASSWORD: "senhaS3gura12*"
            ACCEPT_EULA: "1"